name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: development
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/alert-project/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/alert-project/$IMAGE_NAME:$GIT_TAG
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://northamerica-northeast1-docker.pkg.dev
        docker push northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/alert-project/$IMAGE_NAME:latest
        docker push northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/alert-project/$IMAGE_NAME:$GIT_TAG
